### ISSUE TITLE
Multi-day events cause first day of the event to be always displayed in calendar plugin

### ISSUE THREAD

**Issue by levsha** [usetrmnl/plugins#26]
When a calendar contains a multi-day event to display (school holidays, or vacation for example), then the first day of the even is always shown, even though this day is already in the past.
This causes wasting 1/3 of the screen just to display an one event. And if another multi-day event is to display, just with another starting day, than 2/3 of the screen is wasted.
Multi-day events that are ongoing should be rendered for today only instead.

![Image](https://github.com/user-attachments/assets/8a39a400-b1a4-4903-ae6a-cf0a8e9a85f9)

**Comment by ryanckulp** [comment]
thanks for reporting. it works this way due to receiving inverse feedback previously -- "show a multi day event until it is over."

best solution may be to include yet-another toggle on the calendar settings view so each user can decide. stay tuned for that.

**Comment by levsha** [comment]
> thanks for reporting. it works this way due to receiving inverse feedback previously -- "show a multi day event until it is over."

I totally support showing a multi day even until it is over. Just not the current way.
In the current way multi-day events are rendered for the day when they start (and only for this day!) and cause the start day to stay on the screen as long as a multi-day event is not in the past.
More reasonable would be to render them the way that native Google Calendar shows them for example: show them as full day events for today (and for future days if relevant).

Imagine I have a "March days" multi-day event lasting from 1st till 31st of March.
The current rendering logic will cause it to have "March 1" day to be rendered all the month, with just this event.
Instead, just having "March days" rendered at the very beginning of Today (and two more days in the future if they are still in March) would make much more sense

**Comment by ryanckulp** [comment]
i think this was fixed awhile ago, closing but feel free to re-open if i'm mistaken.

**Comment by levsha** [comment]
> i think this was fixed awhile ago, closing but feel free to re-open if i'm mistaken.

It is NOT fixed, it still behaves exactly how I've mentioned it before: it keeps rendering the day in the past for multi-day event.
Today is Sunday, May25. I have the day before yesterday: Friday, Ma23, rendered, because I have a multi-day event that started on Friday and will end tonight:

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/b6207cb0-9083-46fe-8c82-ab603bcd1642" />

I don't have rights to re-open this issue

**Comment by levsha** [comment]
It is slightly better now, but still not completely fixed.

Right now I have a multi-day event in my calendar for 29 – 30 May 2025. Yesterday, May 29th, it was rendered separately as full day event for both May 29th and May 30th. Today, however, it is just not rendered at all, not for any day.
So it's slightly better now because past days are not rendered anymore and don't eat the space. However multi-day events are not rendered either if this is not the first day of the multi-day event.

Pluging URL is https://usetrmnl.com/plugin_settings/16861/edit

**Comment by ronakjain90** [comment]
Hi @levsha,

This issue is now stale, but I would like to say that the team behind the scenes has shipped 100s of calendar improvements, sometimes fixing the bugs to the open source repository we depend on.

For example, I created a multi-day calendar event between August 6 - August 7, and it correctly shows the event today (August 7th).

<img width="800" height="480" alt="Image" src="https://github.com/user-attachments/assets/3306c996-e800-4966-b232-ad2c5347e479" />

I'm closing this issue. Please feel free to open a new issue if you find something that has to be improved.
